//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProWatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Durumlar
    {
        public byte Id { get; set; }
        public Nullable<byte> MakineId { get; set; }
        public Nullable<byte> DurumTuruId { get; set; }
        public string DurusNedeni { get; set; }
        public Nullable<byte> OperatorId { get; set; }
        public Nullable<byte> TeknikerId { get; set; }
        public string DurusBaslamaZamani { get; set; }
        public string DurusBitisZamani { get; set; }
        public Nullable<int> DurusSuresi { get; set; }
    
        public virtual DurusTurleri DurusTurleri { get; set; }
        public virtual Makineler Makineler { get; set; }
        public virtual Operatorler Operatorler { get; set; }
        public virtual Teknikerler Teknikerler { get; set; }
    }
}
