//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProWatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public byte Id { get; set; }
        public string KullaniciAdi { get; set; }
        public string Parola { get; set; }
        public string Ad { get; set; }
        public string Email { get; set; }
        public string KayıtTarihi { get; set; }
        public string Yetkisi { get; set; }
    }
}
