//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProWatch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProWatchEntities : DbContext
    {
        public ProWatchEntities()
            : base("name=ProWatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Durumlar> Durumlar { get; set; }
        public virtual DbSet<DurusTurleri> DurusTurleri { get; set; }
        public virtual DbSet<Kullanıcılar> Kullanıcılar { get; set; }
        public virtual DbSet<Makineler> Makineler { get; set; }
        public virtual DbSet<Operatorler> Operatorler { get; set; }
        public virtual DbSet<Teknikerler> Teknikerler { get; set; }
        public virtual DbSet<UretimBilgileri> UretimBilgileri { get; set; }
    }
}
