//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProWatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teknikerler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teknikerler()
        {
            this.Durumlar = new HashSet<Durumlar>();
        }
    
        public byte Id { get; set; }
        public Nullable<int> TeknikerSicil { get; set; }
        public string TeknikerAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Durumlar> Durumlar { get; set; }
    }
}
